from . import declaration_cotisation
from . import cotisation_line
from . import abatement_base
from . import movement_employees
from . import declaration_das
from . import lot_declaration_cotisation
from . import res_company
from . import hr_employee
from . import res_partner
from . import activity_code